// packages/cli/src/generators/common/ReadmeGenerator.ts
import { BaseGenerator } from '../baseGenerator';
import { writeFileSafely } from '../utils/fileSystemHelper';
import path from 'path';

export class ReadmeGenerator extends BaseGenerator {
  async generate(): Promise<void> {
    const filePath = path.join(this.projectDir, 'README.md');
    const content = `# ${this.options.projectName}\n\nGenerated by IndigoDB CLI.\n`;
    await writeFileSafely(filePath, content);
  }
}
